---
# - name: get facts
#   ansible.builtin.setup:
#   resgister: output

- name: Debug
  ansible.builtin.debug:
    msg: '{{ ansible_facts }}'
  when: ansible_facts['virtualization_role'] == 'guest'
...
